const typesConstant = {
    FETCH_PRODUCT: 'FETCH_PRODUCT',
    LOADING_PRODUCT: 'LOADING_PRODUCT',
    FILTER_BY_PRICE_DSC: 'FILTER_BY_PRICE_DSC',
    FILTER_BY_PRICE_ASC: 'FILTER_BY_PRICE_ASC',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    SEARCH_PRODUCT: 'SEARCH_PRODUCT',


}

export default typesConstant